feature(front): #22 - drag and drop ressource
Terraform-GUI/terraform-gui pull request #23
Opened 2022-07-26 14:27 UTC by Tan82710

## Description

Please include a summary of the change (features and fixes)

## Related issues

- #22 

## Type of change

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

2022-07-26 18:03 UTC, PIERRONMarc requested changes
Change ta PR pour merge dans dev et pas dans main

2022-07-27 07:19 UTC, Tan82710 commented
> Change ta PR pour merge dans dev et pas dans main

2022-07-27 10:42 UTC, PIERRONMarc approved these changes

2022-07-27 12:34 UTC, lucaslehot reviewed
Est-ce qu'on passerait pas par un context pour tout ce qui est logique ? ça pourrait être pratique pour centraliser les logiques, genre avoir un securityContext et un workbenchContext quelque chose comme ça.

2022-07-28 12:00 UTC, FlorianB98 approved these changes

2022-07-28 12:17 UTC, merged