add(api): #33 - load AWS resources in the database with a command
Terraform-GUI/terraform-gui pull request #34
Opened 2022-08-01 23:54 UTC by PIERRONMarc

## Description

Load AWS resources in the database with a 'load:fixtures' command 

## Related issues

- #33 

## Type of change

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

2022-08-02 08:36 UTC, samuelbelolo requested changes

2022-08-02 08:36 UTC, samuelbelolo commented on api/src/Command/DataFixtures/UserFixtures.php
> +    {
J'avais fait une commande symfony pour creer un user, on la supprime ? on la garde ? on fait un `make fixture`avec tes fixtures et ma commande ? il y avait une verif d'erreur dans la mienne non presente ici, let me know

2022-08-02 08:36 UTC, samuelbelolo commented on api/src/Document/Embed/ResourceArgument.php
>          if (in_array($this->type, $authorizedTypeWhenSettingMax)) {
Pour moi il vaut utiliser un assert et notemment : [Assert\Choice](https://symfony.com/doc/current/reference/constraints/Choice.html#basic-usage)

2022-08-02 10:04 UTC, PIERRONMarc commented on api/src/Command/DataFixtures/UserFixtures.php
> +    {
Ta commande permet de générer un user dynamiquement à partir de ce qu'on renseigne. La mienne uniquement de générer des données fixes. Je pense que c'est complémentaire on peut garder les deux. 

La verif d'erreur est nécessaire parce que tu gères des entrées, mais là c'est le dev qui creer l'objet. J'y vois moins d'interêt.

2022-08-02 10:07 UTC, PIERRONMarc commented on api/src/Document/Embed/ResourceArgument.php
>          if (in_array($this->type, $authorizedTypeWhenSettingMax)) {
J'aurais dis pareil mais l'exception est à destination du dev. L'objet n'a pas vocation à passer dans un validator (example: dans une fixtures). Le client ne va interagir avec cet objet qu'en readonly.

2022-08-02 10:09 UTC, samuelbelolo commented on api/src/Command/DataFixtures/UserFixtures.php
> +    {
Ok on garde les deux, seems good. 

Cependant est-ce que les fixtures purge la base systematiquement ? Dans le cas contraire il pourrait y avoir une erreur sur le assert Unique de l'email

2022-08-02 10:14 UTC, PIERRONMarc commented on api/src/Command/DataFixtures/UserFixtures.php
> +    {
C'est surtout pour du dev. Ici j'ai tenté de répliquer le fonctionnement des [fixtures doctrine](https://symfony.com/bundles/DoctrineFixturesBundle/current/index.html) que je n'ai pas réussi a set up avec mongodb. ça passe par une purge avant chaque initialisation de la base, pour pas mélanger les données j'imagine.

2022-09-12 20:07 UTC, BATABA approved these changes

2022-10-06 10:14 UTC, samuelbelolo approved these changes

2022-10-06 10:14 UTC, merged