Feature/variables handling
Terraform-GUI/terraform-gui pull request #7
Opened 2022-07-25 08:34 UTC by lucaslehot

## Description

Please include a summary of the change (features and fixes)

## Related issues

- #issue_id

## Type of change

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

2022-07-26 11:41 UTC, PIERRONMarc requested changes

2022-07-26 11:41 UTC, PIERRONMarc commented on api/src/Controller/VariableController.php
> +    #[Route('/projects/{project_id}/variables', name: 'get-variables', methods: ['GET'])]
L'user doit être authentifié pour accéder à la route. La protéger par le firewall api (/api).

2022-07-26 11:41 UTC, PIERRONMarc commented on api/src/Controller/VariableController.php
> +    #[Route('/projects/{project_id}/variables', name: 'create-variable', methods: ['POST'])]
L'user doit être authentifié pour accéder à la route. La protéger par le firewall api (/api).

2022-07-26 11:41 UTC, PIERRONMarc commented on api/src/Controller/VariableController.php
> +    #[Route('/projects/{project_id}/variables/{variable_id}', name: 'update-variable', methods: ['PUT'])]
L'user doit être authentifié pour accéder à la route. La protéger par le firewall api (/api).

2022-07-26 11:41 UTC, PIERRONMarc commented on api/src/Controller/VariableController.php
> +    #[Route('/projects/{project_id}/variables/{variable_id}', name: 'delete-variable', methods: ['DELETE'])]
L'user doit être authentifié pour accéder à la route. La protéger par le firewall api (/api).

2022-08-01 23:33 UTC, samuelbelolo requested changes

2022-08-01 23:33 UTC, samuelbelolo commented on api/src/Controller/Api/VariableController.php
> +    #[Route('/projects/{project_id}/variables', name: 'get-variables', methods: ['GET'])]
nomenclature

2022-08-01 23:33 UTC, samuelbelolo commented on api/src/Controller/Api/VariableController.php
> +            $variable->setProjectId($project_id);
D'ou provient le project_id ? Comment est-il généré ? 

Généralement on met ca comme nomenclature de variables : `$project_id` => `$projectId`

2022-08-01 23:33 UTC, samuelbelolo commented on api/src/Form/VariableType.php
> +                    // @TODO: ^ add payload specifications for Assert\Json() ?
@Todo a faire : 

[Assert\Collection](https://symfony.com/doc/current/reference/constraints/Collection.html#basic-usage)

2022-10-09 00:28 UTC, PIERRONMarc commented
Clôture de la PR si abandon de la feature ?

2022-10-09 16:42 UTC, closed without merging