Handling users
Terraform-GUI/terraform-gui pull request #8
Opened 2022-07-25 08:44 UTC by lucaslehot

## Description

Please include a summary of the change (features and fixes)

## Related issues

- #6 

## Type of change

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

2022-07-26 11:42 UTC, PIERRONMarc requested changes

2022-07-26 11:42 UTC, PIERRONMarc commented on api/src/Controller/UserController.php
> +    #[Route('/users/{user_id}', name: 'update-user', methods: ['PUT'])]
L'user doit être authentifié pour accéder à la route. La protéger par le firewall api (/api).

2022-07-26 11:42 UTC, PIERRONMarc commented on api/src/Controller/UserController.php
> +    #[Route('/users/{user_id}', name: 'delete-user', methods: ['DELETE'])]
L'user doit être authentifié pour accéder à la route. La protéger par le firewall api (/api).

2022-07-26 13:12 UTC, samuelbelolo requested changes

2022-07-26 13:12 UTC, samuelbelolo commented on api/src/Controller/UserController.php
> +    #[Route('/users/{user_id}', name: 'update-user', methods: ['PUT'])]
Le controller doit se trouver dans le dossier `Api`

2022-07-26 13:12 UTC, samuelbelolo commented on api/src/Form/UserType.php
> +<?php
Faudrait appeller le form `UserUpdateEmailType.php`

2022-07-26 13:12 UTC, samuelbelolo commented on api/src/Controller/UserController.php
> +
Faut faire valider l'entité User

Le document `User` possède une constrainte sur l'email. Cela permet de verifier que lors de l'update l'user ne renseigne pas l'email d'un autre compte.

2022-07-26 13:12 UTC, samuelbelolo commented on api/src/Controller/UserController.php
> +    #[Route('/users/{user_id}', name: 'update-user', methods: ['PUT'])]
le nom de la route devrait etre `user_update_email`(c'est une convention)
De meme je changerait le nom de la fonction par updateEmail car je pense qu'on va proposer la possibilité de changer le password
comme tu as `#[Route(name: 'user_')]` ligne 17. 
Le name de ta route est : `user_update-user`

2022-07-27 13:29 UTC, samuelbelolo requested changes

2022-07-27 13:29 UTC, samuelbelolo commented on api/src/Controller/Api/UserController.php
> +    #[Route('/users/{user_id}/request-email-update', name: 'request_update_email', methods: ['POST'])]
J'aurais mis un PATCH a la place de POST
et `/users/{user_id}/email` en route

2022-07-27 13:29 UTC, samuelbelolo commented on api/src/Controller/Api/UserController.php
> +                ->html('<p>You have requested an email update. Please click the following link to confirm your new email address.</p> <a href="'.$_ENV['FRONT_URL'].'users/'.$user->getId().'/email-upd
pour la route en front serait : 
```
$_ENV['FRONT_URL'].'/account?confirm-token='.$emailUpdateRequest->getToken().
```

pas besoin de mettre l'user id car avec le token seulement on peut retrouver l'user (avec l'ancien email)

2022-07-27 13:29 UTC, samuelbelolo commented on api/src/Controller/Api/UserController.php
> +                ->html('<p>You have requested an email update. Please click the following link to confirm your new email address.</p> <a href="'.$_ENV['FRONT_URL'].'users/'.$user->getId().'/email-upd
```
$_ENV['FRONT_URL'].'?confirm-token='.$emailUpdateRequest->getToken()
```

2022-07-27 13:29 UTC, samuelbelolo commented on api/src/Controller/UserController.php
> +    #[Route('/users/{user_id}/email-update', name: 'email_update', methods: ['POST'])]
PATCH

`/users/confirm/email`
token dans le form

2022-07-27 13:29 UTC, samuelbelolo commented on api/src/Form/UserUpdateEmailType.php
> +            ->add('email', EmailType::class,
`token` et non `email`

2022-07-27 13:29 UTC, samuelbelolo commented on api/src/Form/UserUpdateEmailType.php
> +use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
a remplacer par : 
`use Symfony\Component\Form\Extension\Core\Type\TextType;`

2022-07-27 13:29 UTC, samuelbelolo commented on api/src/Form/UserUpdateEmailType.php
> +                        new Assert\Email(),
plus de Assert Email

2022-07-27 13:29 UTC, samuelbelolo commented on api/src/Controller/UserController.php
> +            if ($emailUpdateRequest->getCreatedAt()->diff(new \DateTimeImmutable())->s > (int) $_ENV['PASSWORD_RESET_EXPIRATION']) {
`PASSWORD_RESET_EXPIRATION `
creer new env var : 
`EMAIL_UPDATE_RESET_EXPIRATION`

2022-10-06 10:10 UTC, PIERRONMarc approved these changes

2022-10-06 10:13 UTC, samuelbelolo approved these changes

2022-10-06 10:13 UTC, merged